### ISSUE TITLE
Error: Cannot find module './porn-names.js'` after running installation steps

### ISSUE THREAD

**Issue by therollingtester** [crip/crip-names#4]
Steps:
1. Fire up a terminal and run `$ npm install --global crip-names`
2. Run `$ crip-names --help`

Exp:
Examples to be displayed

Act: 

```
Error: Cannot find module './porn-names.js'`

console log:
`npm install --global crip-names
/Users/Viktor/.node/bin/crip-names -> /Users/Viktor/.node/lib/node_modules/crip-names/cli.js
crip-names@1.2.4 /Users/Viktor/.node/lib/node_modules/crip-names
├── unique-random-array@1.0.0 (unique-random@1.0.0)
├── lodash@3.10.1
└── meow@2.1.0 (object-assign@2.1.1, minimist@1.2.0, camelcase-keys@1.0.0, indent-string@1.2.2)
➜  ~  crip-names
module.js:338
    throw err;
          ^
Error: Cannot find module './porn-names.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Viktor/.npm-packages/lib/node_modules/crip-names/index.js:10:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

<img width="702" alt="screen shot 2015-08-30 at 19 18 05" src="https://cloud.githubusercontent.com/assets/3662539/9570053/0a9ea16a-4f4c-11e5-952b-58b5474095c2.png">

**Comment by johnie** [comment]
See [9cc27f2](https://github.com/crip/crip-names/commit/9ef3f529c296bca8ebb9d70c9952856c30147efb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R36) :zap:

**Comment by therollingtester** [comment]
Retested and OK!
